---
output:
  github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->


# National Bridge Inventory

<!-- badges: start -->

<!-- badges: end -->

## Overview

'nbi_package' is an R package containing functions to use for the cleaning and creation of visualizations using the National Bridge Inventory dataset created by the FHWA.


## Installation

You can install the latest version from GitHub with:

```{r}
if(packageVersion("devtools") < "2.4.5") {
  install.packages("devtools")
}
devtools::install_github("The-Pineapple-7/nbi.package")
```

## Usage

* get_country_data, for downloading or reading NBI data of the entire United States.
* get_state_data, for downloading NBI data of individual states.
* LAT_016_conversion and LONG_017_conversion, for converting LAT_016 and LONG_017 data into decimal format.
* STATE_CODE_001_recode, for recoding and renaming STATE_CODE_001.
* RECORD_TYPE_005A_recode, for recoding record type
* ROUTE_PREFIX_005B_recode, for recoding  and renaming route prefix.
* MAINTENANCE_021_recode, for recoding maintenance responsibility.
* OWNER_022_recode, for recoding bridge owner.
* FUNCTIONAL_CLASS_026_recode, for recoding functional classification.
* STRUCTURE_TYPE_043, for recoding the structure type.
